name: splinecam
channels:
  - conda-forge
dependencies:
  - python=3.11
  - tqdm
  - networkx
  - python-igraph
  - ca-certificates
  - openssl
  - jupyter
  - graph-tool
  - certifi
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - livelossplot
